places = ['monterey', 'paris', 'los angles', 'lake tahoe', 'new york city']

print(places)
print(sorted(places))
print(places)
print(sorted(places)
)
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse = True)
print(places)